
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bootbank
    username: dongjun
    password: 1204#
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: API-KEY

logging:
  level:
    root: info
    web: info
    sql: error
    org.springframework: error
    org.hibernate: error
    com.miniproject: error

chatgpt:
  api-key: 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
openai:
  api-key : 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


